import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import StoreProvider from "../StoreProvider";
import SessionWrapper from "@/provider/session";
import AdminNavbar from "@/components/adminNavbar";
import { auth } from "@/auth"
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth()
    if (!session || !session.isAdmin) {
        redirect("/user/login")
    }
    return (
        <StoreProvider>
            <SessionWrapper>
                <html lang="en">

                    <body className={inter.className}>
                        <AdminNavbar />
                        {children}
                    </body>
                </html>
            </SessionWrapper>
        </StoreProvider>
    );
}
